### ISSUE TITLE
AttributeError("'ComicImporter' object has no attribute '_process_series_without_cvid'",)

### ISSUE THREAD

**Issue by gfriloux** [hmhrex/Tenma#30]
Hello!

I am trying to get Tenma running here.
When i try to import comics, i get the following error logs from celery process : 
```
[2017-07-22 15:36:17,773: INFO/MainProcess] Received task: import_comic_files_task[45029f5f-40ee-4761-9911-008599e6e249]
[2017-07-22 15:36:19,361: ERROR/MainProcess] Task import_comic_files_task[45029f5f-40ee-4761-9911-008599e6e249] raised unexpected: AttributeError("'ComicImporter' object has no attribute '_process_series_without_cvid'",)
Traceback (most recent call last):
  File "/usr/share/webapps/tenma/venv/lib/python3.6/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/share/webapps/tenma/venv/lib/python3.6/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/share/webapps/tenma/venv/tenmaserver/comics/tasks.py", line 8, in import_comic_files_task
    importer.import_comic_files()
  File "/usr/share/webapps/tenma/venv/tenmaserver/comics/utils/comicimporter.py", line 99, in import_comic_files
    self._process_series_without_cvid(entry.name)
AttributeError: 'ComicImporter' object has no attribute '_process_series_without_cvid'
```

I have no idea what to look to get you more outputs.
The fact is that i know nothing to python/celery, so i would gladly help by giving you more outputs, but please dont get too technical :)

**Comment by hmhrex** [comment]
Thanks for this stack trace! This is a bug plain and simple. I'll get this fixed up for you.

**Comment by gfriloux** [comment]
Ok nice ! thanks!

**Comment by gfriloux** [comment]
I confirm the bug is fixed on my side.
I now see the comics !
